In [1]:
# imports
import random as rd

In [2]:
rd.random()

0.9599218103574184

In [3]:
rd.randint(2, 100)

75

In [4]:
rd.randrange(-9,9,3)

-9

In [5]:
rd.uniform(-10,10)

-3.40870516112886

In [6]:
ran_lat = rd.randint(-90, 89) + rd.random()
ran_lat

-48.7066991946427

In [7]:
x = 1
latitudes = []
while x < 11:
    random_lat = rd.randint(-90, 89) + rd.random()
    latitudes.append(random_lat)
    x += 1
latitudes

[-18.772863276223067,
 50.87302325706728,
 40.2675322450423,
 -67.04986111748373,
 -74.75239983575261,
 -71.6512602338328,
 48.06459931616835,
 -74.92094188526134,
 -66.54294402713984,
 -55.797160082183495]

In [8]:
x = 1
longitudes = []
while x < 11:
    random_long = rd.randrange(-180, 179, 1)
    longitudes.append(random_long)
    x += 1
longitudes

[136, 160, -117, -93, -163, 119, 171, 66, -78, 133]

In [9]:
x = 1
longitudes = []
while x < 11:
    random_long = rd.uniform(-180, 180)
    longitudes.append(random_long)
    x += 1
longitudes

[-80.96350673252205,
 5.4905339457679645,
 134.96070873200784,
 99.97000267458094,
 -36.171844390209145,
 -126.31286031308193,
 -89.66075700534601,
 -157.7448122293781,
 168.23010124619304,
 -79.49108995931813]

In [10]:
# Import the NumPy module.
import numpy as np

In [11]:
np.random.uniform(-90.000, 90.000, size=50)

array([-66.65207433, -59.17674316,  -3.82856746,  14.7992513 ,
       -83.94410128,  48.25176988,  44.89657344, -27.81328896,
       -82.79618261,   5.8773571 ,  16.39467049,  48.05210195,
        61.51163778,  55.18359217,  69.47592439,  76.84843945,
         2.05472039, -31.2873227 ,   8.94128248,  42.26187644,
       -39.83984479, -73.16681807, -68.68711172,  55.15279492,
        88.83194578, -24.15123258, -35.76289754,  35.8620519 ,
       -83.54647064,  57.06746118,   0.49215451,  79.39062727,
       -74.52470784, -22.70174541,  -2.52369582, -68.24173109,
        76.99753308, -80.70067103,  20.34203502,  32.75344486,
        17.63467146,  46.13450173, -69.06499511,  38.8132362 ,
        85.06055523,  79.98497034,  10.2641033 ,   0.84585981,
       -30.58414692, -84.47642732])

In [12]:
coords = (np.random.uniform(-90, 90, size=50), np.random.uniform(-180, 180, size=50))

In [13]:
coords

(array([  0.4643122 , -44.62990182, -55.61750162,  -5.5711495 ,
        -74.92149895,  85.07752145, -61.35120877,  29.52385867,
        -87.11870139,  52.37916292, -27.85236848,  32.0152623 ,
        -61.51810188,  23.40021032, -78.82345927,  -1.77290465,
        -24.59221248,  72.97122195, -19.21114787,  76.29312074,
        -87.77926186, -53.17810376, -79.98560155, -68.57178035,
          6.20899601,  78.68466955, -34.29148125, -11.58015611,
         80.93979985, -78.35175846,  31.16802334, -65.28075691,
         51.59713462, -42.46385157, -64.11034068, -20.77720056,
         64.68295659, -71.48043151, -57.87452286, -12.01791342,
        -18.95074557, -79.55392512,  44.4824763 ,  78.60123924,
         -2.32562517,  57.03912007,  -2.52828093,  67.99321604,
        -87.80373026, -48.47320538]),
 array([  53.99733508,  -79.80952811,  135.09982655,   89.59811677,
          -4.63559236,  117.06719112,  113.36144095, -108.74150592,
         -47.01153471,   61.82621485,  -44.74914935,   93.

In [14]:
# Import timeit.
import timeit

In [15]:
%timeit np.random.uniform(-90, 90, size=1500)

16.3 µs ± 485 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = rd.randint(-90, 90) + rd.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

2.38 ms ± 28.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
